### ISSUE TITLE
Модель черновиков непонятная

### ISSUE THREAD

**Issue by kelizarov** [vladimirbokor/DRF-news#2]
Не совсем понятно зачем делать дубликат модели для черновиков и постов отдельно, при том что они имеет одинаковую структуру. Из-за такой лишней сложности у меня не получилось создать пост с новостью.

**Comment by vladimirbokor** [comment]
Изначально делал чтобы посты наследовались от черновиков, но с наследованием вышла проблема в том, что не выполнялось вот это условие из задания:

> Новость в админке должна иметь возможность иметь черновики — то есть мы должны иметь возможность в админке вносить изменения, но не опубликовать их. По АПИ отдаем только опубликованные новости.

(при наследовании) Как только я изменял черновик, опубликованная новость тут же менялась. Я читал про наследовании в документации, и там написано, что для использования независимых таблиц бд нужно Multi-table наследование. Как бы исходя из документации, базовое наследование должно быть именно таким. Но почему-то выходит, как будто я использую абстрактуную модель. Поэтому вышли две индентичные модели.

**Comment by kelizarov** [comment]
Городить дубликатами моделей довольно изощренное занятие. Лучше переделай это под одну модель и добавь флаг черновика для постов.

**Comment by vladimirbokor** [comment]
Так было изначально, но условие что черновики должны быть независимы от постов сломало это. 
Флаг же не дает возможности редактировать черновик без обновления поста, если он уже был опубликован.

**Comment by kelizarov** [comment]
Ну а что мешает сделать дополнительный эндпойнт например, который создавал копию поста и прописывал соответстующий флаг. :) (например опубликованную статью перевести в черновик, а затем опубликовать как новый)

**Comment by vladimirbokor** [comment]
> Новость в админке должна иметь возможность иметь черновики — то есть мы должны иметь возможность в админке вносить изменения, но не опубликовать их. По АПИ отдаем только опубликованные носвости.

Вот из этого я понял, что должно быть две модели. 
Что во время редакции черновика, опубликованная новость так и оставалась висеть. А сохранение черновика не приводило бы к обновлению новости. Только после ручного "опубликовать" новость бы заменялась.
Постараюсь что-нибудь придумать)
