### ISSUE TITLE
Во вьюхах где требуется аутенфикация автора или админа возвращать статус not_authorized

### ISSUE THREAD

**Issue by kelizarov** [vladimirbokor/DRF-news#3]
Посмотри тоже в доках реста как пермишены работают. Возвращать 404 из-за того что у юзера нет прав двольно запутанное решение.

**Comment by vladimirbokor** [comment]
> (черновики и пользователи доступны только админам, остальным возвращать 404, не 403, чтобы не показать само наличие такого API)

В условиях на ризомма было вот так, поэтому и 404

**Comment by kelizarov** [comment]
Проблема в том что ты явно рейзишь 404 во вьюхах в момент когда ты запрашиваешь кверисет. У реста есть отдельный механизм для этого который позволяет настроит уровни доступа ко вьюхам.

**Comment by vladimirbokor** [comment]
Исправлено в #4, проверка теперь идет в permissions
